### ISSUE TITLE
Missing codes about CIFAR-10 & CIFAR-10-LT?

### ISSUE THREAD

**Issue by machengcheng2016** [frank-xwang/debiased-pseudo-labeling#1]
Love this work!
I try to utilize [FixMatch-pytorch](https://github.com/kekmodel/FixMatch-pytorch) to reimplement this work, but fail to get results reported in the paper.
Would you please release the codes about CIFAR-10 & CIFAR-10-LT?

**Comment by frank-xwang** [comment]
Hi, sorry for the late reply. Currently, this repo is only used to reproduce experimental results on large-scale datasets, such as ImageNet (we may still release code on small-scale datasets, but with low priority). However, I would be happy to help you reproduce these results. Can you share more information with me? Thanks!

**Comment by frank-xwang** [comment]
Close this issue for now. If you are concerned about posting your training details on Github, you can also send an email to xdwang@eecs.berkeley.edu. Thanks
