### ISSUE TITLE
Are there indexes for ImageNet-LT?

### ISSUE THREAD

**Issue by linzhiqiu** [frank-xwang/debiased-pseudo-labeling#4]

**Comment by linzhiqiu** [comment]
Or ImageNet127, as reported in CReST?

**Comment by frank-xwang** [comment]
Please check [dataset preparation section of https://github.com/frank-xwang/RIDE-LongTailRecognition](https://github.com/frank-xwang/RIDE-LongTailRecognition#dataset-preparation) to get the indexes for ImageNet-LT. For ImageNet-127, we didn't try this dataset. You need to check the CResST repo to prepare for ImageNet-127.
